#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client' #, "=1.1.2"
cookbook 'apt', '= 1.9.0'
cookbook 'git'
cookbook 'build-essential'
cookbook 'postfix'
cookbook 'ntp'
cookbook 'mongodb', :github => 'edelight/chef-mongodb'
cookbook 'mysql'
cookbook 'xml'
cookbook 'xslt'

cookbook 'rvm', :github => 'theodi/chef-rvm.git'
cookbook 'envbuilder', :github => 'theodi/chef-envbuilder.git'
