#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client' #, "=1.1.2"
cookbook 'apt', '= 1.9.0'
cookbook 'git'
cookbook 'build-essential'
cookbook 'postfix'
cookbook 'ntp'
cookbook 'mongodb', :github => 'edelight/chef-mongodb'