#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'chef-client' #, "=1.1.2"
cookbook 'apt', '= 1.9.0'
cookbook 'git'
cookbook 'build-essential'
cookbook 'postfix'
cookbook 'ntp'
cookbook 'mongodb', :github => 'edelight/chef-mongodb'
cookbook 'mysql'
cookbook 'xml'
cookbook 'xslt'
cookbook 'nginx'
cookbook 'nodejs'
cookbook 'capybara-webkit', :github => 'RichGuk/chef-capybara-webkit'
cookbook 'memcached'
cookbook 'fail2ban', :github => 'opscode-cookbooks/fail2ban'
cookbook 'varnish', :github => 'opscode-cookbooks/varnish'
cookbook 'cloud_monitoring', :github => 'racker/cookbook-cloudmonitoring'
cookbook 'ImageMagick', :github => 'opscode-cookbooks/imagemagick'
cookbook 'statsd', :github => 'librato/statsd-cookbook'
cookbook 'java', :github => 'opscode-cookbooks/java'
cookbook 'elasticsearch', :github => 'elasticsearch/cookbook-elasticsearch'

cookbook 'rvm', :github => 'fnichol/chef-rvm'
cookbook 'envbuilder', :github => 'theodi/chef-envbuilder'
cookbook 'dictionary', :github => 'theodi/chef-dictionary'
cookbook 'sqlite', :git => 'git@github.com:theodi/chef-sqlite.git'
cookbook 'libcurl', :git => 'git@github.com:theodi/chef-libcurl.git'

