#!/usr/bin/env ruby
#^syntax detection

ecosystem "quirkafleeg" do
  container "mongo-quirkafleeg-cucumber-01" do
    distro "ubuntu"
    release "precise"
    persist true
    ip "192.168.99.10"
    mac "00:00:5e:a2:c8:c9"
    chef_client (
                    {
                        :environment => "cucumber",
                        :run_list    => [
                            "role[base]",
                            "role[chef-client]",
                            "role[mongodb]"
                        ]
                    }
                )
  end

  container "mysql-quirkafleeg-cucumber" do
    distro "ubuntu"
    release "precise"
    persist true
    ip "192.168.99.20"
    mac "00:00:5e:6a:94:a2"
    chef_client (
                    {
                        :environment => "cucumber",
                        :run_list => [
                            "role[quirkafleeg]",
                            "role[base]",
                            "role[chef-client]",
                            "role[mysql]"
                        ]
                    }
                )
  end
end

