#!/usr/bin/env ruby
#^syntax detection

ecosystem "quirkafleeg" do
  container "mongo-01" do
    distro "ubuntu"
    release "precise"
    persist true
    ip "192.168.99.10"
    mac "00:00:5e:a2:c8:c9"
    chef_client (
                    {
                        :run_list => [
                            "role[base]",
                            "role[chef-client]",
                            "recipe[postfix]",
                            "recipe[ntp]"
                        ]
                    }
                )
  end
end

