# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Auto-generated by cucumber-chef v#{Cucumber::Chef::VERSION} on #{Time.now.utc} -- DO NOT EDIT!

# Vagrant v1 Configuration
###########################
Vagrant::Config.run do |config|
  config.vm.define "test-lab-#{ENV['USER']}".downcase do |test_lab|
    test_lab.vm.box     = "precise64"
    test_lab.vm.box_url = "http://files.vagrantup.com/precise64.box"
    test_lab.vm.network :hostonly, "192.168.33.10"

    test_lab.vm.customize ["modifyvm", :id, "--cpus", 4]
    test_lab.vm.customize ["modifyvm", :id, "--memory", 4096]
  end
end

# Vagrant v2 Configuration
###########################
Vagrant.configure("2") do |config|
  config.vm.define "test-lab-#{ENV['USER']}".downcase do |test_lab|
    test_lab.vm.box     = "precise64"
    test_lab.vm.box_url = "http://files.vagrantup.com/precise64.box"
    test_lab.vm.network :private_network, :ip => "192.168.33.10"

    test_lab.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--cpus", 4]
      vb.customize ["modifyvm", :id, "--memory", 4096]
    end

    test_lab.vm.provision :shell,
                          :inline => "head -$((`wc -l /etc/rc.local | cut -d ' ' -f 1` - 1)) /etc/rc.local > /tmp/rc.local && for line in '/sbin/iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE' '/sbin/iptables -A FORWARD -i eth0 -o br1 -m state --state RELATED,ESTABLISHED -j ACCEPT' '/sbin/iptables -A FORWARD -i eth1 -o br1 -j ACCEPT' ; do echo ${line} >> /tmp/rc.local ; done && echo 'exit 0' >> /tmp/rc.local && sudo cp /tmp/rc.local /etc/ && sudo /etc/rc.local 2> /dev/null && echo '1' | sudo tee /proc/sys/net/ipv4/ip_forward && echo net.ipv4.ip_forward=1 | sudo tee -a /etc/sysctl.conf > /dev/null"
  end
end
